### ISSUE TITLE
API-Key config-checks always fails

### ISSUE THREAD

**Issue by juergen6** [johi123/it523-backend#1]
https://github.com/johi123/it523-backend/blob/f672c036f7455ad24f2ce65c0a582c7cfa5706fa/src/configs/app.config.ts#L12

Hier fehlt ein `!`vor `POLYGON_API_TOKEN`. Sonst sagt er "API Keys fehlen", obwohl sie eh da sind.

**Comment by johi123** [comment]
Danke, habe ich ausgebessert 😄
